name: Build LaTeX TikZ Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends texlive-base texlive-latex-extra

      - name: Build LaTeX projects
        run: |
          find . -type f -name "main.tex" -exec sh -c 'pdflatex -interaction=nonstopmode -halt-on-error "$1" && echo "Build completed successfully."' _ {} \; || echo "Build failed."

      - name: Archive all PDFs
        run: |
          find . -type f -name "main.pdf" -exec sh -c 'cp "$1" "${1%.pdf}_copy.pdf"' _ {} \;
          find . -type f -name "*_copy.pdf" -exec sh -c 'echo "::set-output name=pdf_path::$(realpath $1)"' _ {} \;
        id: archive

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with:
          name: PDFs
          path: ${{ steps.archive.outputs.pdf_path }}
